version: "3"

services:
    app:
        image: lscr.io/linuxserver/nginx:1.24.0
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Paris
            COMPOSER_NO_DEV: 1
        volumes:
            - ./src:/config/www
            - ./nginx/default.conf:/config/nginx/site-confs/default.conf
        restart: unless-stopped
        working_dir: /config/www
        depends_on:
            - db
            - redis
        tty: true

    # SQL service
    db:
        image: mariadb:lts-jammy
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME:-app}
            MYSQL_USER: ${DATABASE_USER:-admin}
            MYSQL_PASSWORD: ${DATABASE_PASS:-secret}
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            TZ: ${TZ:-UTC}
        volumes:
            - mysql:/var/lib/mysql
        tty: true

    # Cache service
    redis:
        image: redis:alpine
        restart: unless-stopped
        environment:
            TZ: ${TZ:-UTC}
        volumes:
            - redis:/data
        tty: true

    # Node runtime
    bun-node:
        image: oven/bun:alpine
        environment:
            TZ: ${TZ:-UTC}
            NODE_ENV: development
        volumes: [./src:/app]
        ports: [5173:5173]
        working_dir: /app
        user: "1000"
        profiles: ["dev"]
        tty: true

    # SMTP testing
    mailpit:
        image: axllent/mailpit:latest
        environment:
            TZ: ${TZ:-UTC}
        ports:
            - "8025:8025"
        expose:
            - "1025"
        profiles: ["dev"]
        tty: true

# Persistent data volumes
volumes:
    mysql:
    redis:
