version: "3"

services:
    app:
        image: lscr.io/linuxserver/nginx:1.24.0
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Berlin
            COMPOSER_NO_DEV:
        volumes:
            - ./src:/config/www
            - ./nginx/default.conf:/config/nginx/site-confs/default.conf
        ports:
            - 80:80
            # - 443:443
        restart: unless-stopped
        working_dir: /config/www
        depends_on:
            - redis
            - db
        tty: true

    # MariaDB service
    db:
        image: mariadb:lts-jammy
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME:-app}
            MYSQL_USER: ${DATABASE_USER:-admin}
            MYSQL_PASSWORD: ${DATABASE_PASS:-secret}
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            TZ: ${TZ:-UTC}
        volumes:
            - mysql:/var/lib/mysql
        tty: true
    # Redis service
    redis:
        image: redis:alpine
        restart: unless-stopped
        environment:
            TZ: ${TZ:-UTC}
        volumes:
            - redis:/data
        tty: true

# Persistent data volumes
volumes:
    mysql:
    redis:
