version: "3"

services:
    # Nginx and PHP-FPM service
    app:
        build: ./config
        restart: unless-stopped
        environment:
            TZ: ${TZ:-UTC}
            PHP_DATE_TIMEZONE: ${TZ:-UTC}
            WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT:-/app/public}
            PHP_DISMOD:
            COMPOSER_NO_DEV:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS:
        volumes:
            - ./src:/app
        ports:
            - "${APP_HOST_PORT:-8080}:80"
        working_dir: /app
        depends_on:
            - db
            - redis
        tty: true
    # MariaDB service
    db:
        image: mariadb:lts-jammy
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME:-app}
            MYSQL_USER: ${DATABASE_USER:-admin}
            MYSQL_PASSWORD: ${DATABASE_PASS:-secret}
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            TZ: ${TZ:-UTC}
        volumes:
            - mysql:/var/lib/mysql
        tty: true
    # Redis service
    redis:
        image: redis:alpine
        restart: unless-stopped
        environment:
            TZ: ${TZ:-UTC}
        volumes:
            - redis:/data
        tty: true

# Persistent data volumes
volumes:
    mysql:
    redis:
