services:
    app:
        environment:
            COMPOSER_NO_DEV: 0
        volumes:
            - ./src:/config/www
            - ./nginx/default.conf:/config/nginx/site-confs/default.conf
        ports:
            - 80:80
            - 443:443
